export const PROFILE_BEGIN = 'PROFILE_BEGIN';
export const PROFILE_ERROR = 'RPOFILE_ERROR';
export const PROFILE_CLEAN = 'PROFILE_CLEAN';
export const PROFILE_LOADING_TEXT = 'PROFILE_LOADING_TEXT';

export const PROFILE_GET_USER = 'PROFILE_GET_USER';
export const DETAIL_BEGIN = 'DETAIL_BEGIN';
export const PROFILE_STORE_USER = 'PROFILE_STORE_USER';

export const PROFILE_UPDATE_USER = 'PROFILE_UPDATE_USER';
