/*
  profile page redux types
*/
export const PROFILE_BEGIN = 'PROFILE_BEGIN';
export const PROFILE_ERROR = 'RPOFILE_ERROR';
export const PROFILE_CLEAN = 'PROFILE_CLEAN';
export const PROFILE_LOADING_TEXT = 'PROFILE_LOADING_TEXT';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
export const PROFILE_INFO = 'PROFILE_INFO';
export const PROFILE_END = 'PROFILE_END';

export const PROFILE_GET_USER = 'PROFILE_GET_USER';
export const DETAIL_BEGIN = 'DETAIL_BEGIN';
export const PROFILE_STORE_USER = 'PROFILE_STORE_USER';

export const PROFILE_UPDATE_USER = 'PROFILE_UPDATE_USER';
export const PROFILE_UPDATE_PASSWORD = 'PROFILE_UPDATE_PASSWORD';

export const PROFILE_GET_BOOKMARKS = 'PROFILE_GET_BOOKMARKS';
export const BOOKMARKS_BEGIN = 'BOOKMARKS_BEGIN';
export const PROFILE_STORE_BOOKMARKS = 'PROFILE_STORE_BOOKMARKS';

export const PROFILE_GET_RECIPES = 'PROFILE_GET_RECIPES';
export const RECIPES_BEGIN = 'RECIPES_BEGIN';
export const PROFILE_STORE_RECIPES = 'PROFILE_STORE_RECIPES';
export const PROFILE_REMOVE_RECIPE = 'PROFILE_REMOVE_RECIPE';

export const PROFILE_LOADMORE_RECIPES = 'PROFILE_LOADMORE_RECIPES';
export const PROFILE_LOADMORE_RECIPES_SUCCESS = 'PROFILE_LOADMORE_SUCCESS';

export const PROFILE_LOADMORE_BOOKMARKS = 'PROFILE_LOADMORE_BOOKMARKS';
export const PROFILE_LOADMORE_BOOKMARKS_SUCCESS =
  'PROFILE_LOADMORE_BOOKMARKS_SUCCESS';
