/*
  create reducer action types
*/

export const BEGIN_CATEGORIES = 'BEGIN_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SUCCESS_CATEGORIES = 'SUCCESS_CATEGORIES';

export const CREATE_SUBMIT_RECIPE = 'CREATE_SUBMIT_RECIPE';
export const CREATE_LOADING_TEXT = 'CREATE_LOADING_TEXT';

export const CREATE_ERROR = 'CREATE_ERROR';
export const CREATE_CLEAN = 'CREATE_CLEAN';
export const CREATE_BEGIN = 'CREATE_BEGIN';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
