/*
  category related action types
*/
export const CATEGORY_BEGIN = 'CATEGORY_BEGIN';
export const CATEGOR_ERROR = 'CATEGOR_ERROR';
export const CATEGORY_CLEAN = 'CATEGORY_CLEAN';
export const CATEGORY_CLEAR_ERROR = 'CATEGORY_CLEAR_ERROR';
export const CATEGORY_END = 'CATEGORY_END';

export const CATEGORY_GET_RECIPES = 'CATEGORY_GET_RECIPES';
export const CATEGORY_STORE_RECIPES = 'CATEGORY_STORE_RECIPES';

export const CATEGORY_LOADMORE = 'CATEGORY_LOADMORE';
export const CATEGORY_LOADMORE_LOADING = 'CATEGORY_LOADMORE_LOADING';
export const CATEGORY_LOADMORE_SUCCESS = 'CATEGORY_LOADMORE_SUCCESS';

export const CATEGORY_SORT = 'CATEGORY_SORT';
export const CATEGORY_SORT_RESET = 'CATEGORY_SORT_RESET';
