/*
  update types
*/

export const UPDATE_BEGIN = 'UPDATE_BEGIN';
export const UPDATE_INIT = 'UPDATE_INIT';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_MESSGAGE = 'UPDATE_MESSGAGE';
export const UPDATE_CLEAN = 'UPDATE_CLEAN';
export const UPDATE_LOADING_TEXT = 'UPDATE_LOADING_TEXT';
export const UPDATE_CLEAR = 'UPDATE_CLEAR';

export const UPDATE_GET_RECIPE = 'UPDATE_GET_RECIPE';
export const UPDATE_STORE_RECIPE = 'UPDATE_STORE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
